[build]
  command = "ng build"
  functions = "netlify/functions"
  publish = "dist/front/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[dev]
  framework = "angular"
  command = "ng serve"

[[edge_functions]]
  function = "angular-ssr"
  pattern = "/*"